### ISSUE TITLE
yarn-workspaces.js is not published

### ISSUE THREAD

**Issue by promontis** [tsedio/tsed-monorepo-utils#39]
It seems the `yarn-workspaces.js` file is not included in the npm package.

**Comment by Romakita** [comment]
But is it, I use this module on another project :)

**Comment by Romakita** [comment]
ok I see the issue. I forgot to use the correct bundler for this package.

**Comment by promontis** [comment]
Yeay :)

**Comment by Romakita** [comment]
Release is in progress. It should be better :)

**Comment by promontis** [comment]
\o/

**Comment by promontis** [comment]
works :) thnx for the quick fix
